CIS-Projects-in-CS-S21/kic-frontend

- Personal-Page/PersonalPage.js
- User-Authentication/LogIn.js
- User-Authentication/SignUp.js
- User-Authentication/TokenManager.js
-Fix login bug
-Detect running in production vs development
-Implement functions for managing session tokens through AsyncStorage
> Login bug fix and methods for session token management

- package.json
Added AsyncStorage dependency so the problem builds and deploys properly
> Added async-storage dependency

- Components/AddFriendButton.js
- Components/ProfileHeader.js
- Components/UserBlurb.js
- Personal-Page/FriendsList.js
- Personal-Page/FriendsPage.js
- Personal-Page/PersonalPage.js
- Personal-Page/PersonalPageNav.js
The baseline for the friends page
> Friends page baseline

- User-Authentication/LogIn.js
Add import statement for KIC_Style in login to fix page loading issues
> Import KIC_Style in LogIn

- Components/FeedHeader.js
- Components/FeedPost.js
- User-Feed/UserFeed.js
- yarn.lock
Created a user feed baseline for future integration, with a feed header and feed post being held within user feed.
> User feed baseline

- README.md
Updated deployment page, demo instructions, and v2 release notes
> v2 release notes and updated demo instructions

- Components/CommentSection.js
- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
- Components/PostDetails.js
- Personal-Page/FriendsList.js
- Personal-Page/PersonalPage.js
- Personal-Page/PersonalPageNav.js
Optimized Friends page and DetailedPostView page for mobile. For DetailedPostView, a mobile and web version of the page was created.
> Mobile optimization

- Components/PostsGrid.js
- Components/ProfileHeader.js
- Personal-Page/FriendsList.js
- Personal-Page/FriendsPage.js
- Personal-Page/PersonalPage.js
Integrates basic user details into friends page and passes username and userid as props into ProfilePage components for future use in media integration
> Basic friends page integration

- Components/RequestBlurb.js
- Personal-Page/FriendsPage.js
- Personal-Page/RequestsList.js
Implement baseline views and buttons associated with creating, accepting and rejecting friend requests.
> Baseline add friends functionality

- Explore-Page/Explore.js
- Mental-Health/FindHelp.js
- Mental-Health/MentalHealthLog.js
- Mental-Health/MoodHistory.js
- Personal-Page/FriendsPage.js
- Personal-Page/PersonalPage.js
- Post/Post.js
- User-Authentication/LogIn.js
- User-Authentication/SignUp.js
- User-Feed/UserFeed.js
Using SafeAreaView to seamlessly have status bar across pages on different platforms
> Allowing for status bar to be visible across different platforms

- Components/Style.js
- Mental-Health/MentalHealthLog.js
- Personal-Page/PersonalPage.js
- package.json
- yarn.lock
Developed UI for mental health log UI with scale, journal entry, and date/time tracking functionality. Improved styling of Personal Page and Mental Health Log. Integration is still needed. Works on iOS, Android, and Web.
> Mental health UI

- Components/UserBlurb.js
- Personal-Page/FriendsList.js
- Personal-Page/RequestsList.js
Implemented a friendship checker in UserBlurb that checks for an existing friendship between that user and the active user. The AddFriendButton is only visible on that UserBlurb if there is not already a friendship.
> Only allow AddFriend functionality on userblurb if users are not already friends

- Components/AddFriendButton.js
- Components/ProfileHeader.js
- Components/RequestBlurb.js
- Components/UserBlurb.js
- Managers/TokenManager.js
- Personal-Page/FriendsList.js
- Personal-Page/FriendsPage.js
- Personal-Page/PersonalPageNav.js
- Personal-Page/RequestsList.js
- Personal-Page/UserPage.js
Completes integration of friends page to:
-Display friend list of a user accurately
-Display pending friend reqs list of active user accurately
-Allow active user to view another user's profile and friends by clicking on the user's profile picture in the userblurb
-Allow active user to send friend reqs and remove friends
-Allow active user to accept/refuse friend reqs
> Completed friends page integration

- Components/Style.js
- Post/Post.js
- Post/PostInfo.js
Fixed styling when posting picture to be more uniform and cohesive. Fixed bug when posting on web that allows camera preview to appear. Changed settings to post only images, not images and videos, while fixing video uri issues. Camera and image library for posting now work on iOS, Web, and Android with better UI.
> Post page styling

- Components/Style.js
- Tests/UploadingMedia.test.js
- Tests/UserAuth.test.js
Added Jest Testing for uploading images and also for user authentication. Tests Media Storage client.
> Post page jest testing

- Components/KIC_Image.js
- Components/PostsGrid.js
- Personal-Page/PersonalPage.js
- Personal-Page/ProfilePost.js
- Post/PostInfo.js
Fixes KIC_Image to convert the correct uri to base64 and integrates profile page with media service to display user's posts on their profile. Also links KIC_Image with DetailedPostView, to allow the user to click on the image and be taken to its DetailedPostView page.
Currently has a bug that causes an ERR_INVALID_URL when fetching some images.
> Profile posts integration

- App.js
- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
- Components/FeedHeader.js
- Components/Style.js
- Explore-Page/Explore.js
- Home-Page/HomePage.js
- Home-Page/HomePageMobile.js
- Home-Page/HomePageNav.js
- Home-Page/HomePageWeb.js
- Mental-Health/FindHelp.js
- Mental-Health/MentalHealthLog.js
- Mental-Health/MoodHistory.js
- Personal-Page/FriendsPage.js
- Personal-Page/PersonalPage.js
- Post/Post.js
- User-Authentication/SignUp.js
- User-Feed/UserFeed.js
- package.json
- yarn.lock
This adds a homepage for web and mobile, along with adding a header to each page that has a functional back button and log out button.
> Home page and header added to all pages

- Components/CommentSection.js
- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
- Components/KIC_Image.js
- Components/PostDetails.js
- Components/PostsGrid.js
- Components/Style.js
- Components/UserBlurb.js
- Personal-Page/PersonalPage.js
- Personal-Page/ProfilePost.js
- Personal-Page/UserPage.js
- Post/PostInfo.js
Integrates post uri and metadata into DetailedPostView for web and mobile. Also implements post commenting feature.
> DetailedPostView integration

- Components/KIC_Image.js
- Components/PostsGrid.js
- Managers/ClientManager.js
- Post/PostInfo.js
- gen/proto/media_pb.d.ts
- gen/proto/media_pb.js
- util/BytesDecoder.js
Fixed KIC_Image to download and display images correctly, minor styling fix on personal page
> KIC_Image fix

- Components/Style.js
- Explore-Page/Explore.js
Add user blurbs that users can friend request on explore page
> Added mock explore page

- Components/FeedPost.js
- User-Feed/UserFeed.js
A user feed is created based off of logged in user's friends posts through a stream.
> User feed integration

- Components/FeedPost.js
- Components/KIC_Image.js
- TabNavigation.js
- User-Feed/UserFeed.js
- User-Feed/UserFeedNav.js
Fix bugs accessing DPV and displaying correct information by adding a UserFeedNav
> DPV bug fixes

- Explore-Page/ExploreNav.js
- Personal-Page/PersonalPage.js
- TabNavigation.js
Adds an explore nav to allow users to access other users' profile pages and friends lists
> Explore nav

- Components/DetailedPostViewWeb.js
- Personal-Page/PersonalPage.js
- User-Feed/UserFeed.js
After posting a picture or having a friend post a picture, navigating to the user feed or personal page reloads the page to include new content. Also includes a fix for the DPV of web when deleting posts.
> Reload feature added to user feed and personal page

- README.md
v3 release notes and updated demo instructions
> README v3.0.0 updates

- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
- Components/PostDetails.js
- Components/PostsGrid.js
- Components/ProfileHeader.js
- Components/ProfilePicture.js
- Components/UserBlurb.js
- Personal-Page/PersonalPage.js
- Personal-Page/UserPage.js
-Created a ProfilePicture component that, given a userid, searches for that user's profile picture and displays it, or otherwise displays a default image
-ProfilePictures now link to user pages
-Other users' profiles now display their posts correctly
-User profiles now accessible through explore tab
-Mobile version of DetailedPostView has been integrated with comments
> Linked profile images and accessible user profile pages

- Explore-Page/Explore.js
Added explore page functionality. Shows friend suggestion on load, and when user is searched, displays user if exists.
> Explore integration

- App.js
- Components/HealthLogBlurb.js
- Components/Style.js
- Mental-Health/MentalHealthLog.js
- Mental-Health/MoodHistory.js
- Post/Post.js
- Post/PostInfo.js
- Post/PostNav.js
- gen/proto/health_grpc_pb.d.ts
- gen/proto/health_grpc_pb.js
- gen/proto/health_pb.d.ts
- gen/proto/health_pb.js
User can now  save entry of mental health log into database, and view it on mood history page. User can click on the date to see the entry. User can delete the entry for a particular date. User now logs mental health from -5 bad to 5 good.
> Health integration

- Mental-Health/FindHelp.js
- Mental-Health/MapView.js
- Personal-Page/PersonalPageNav.js
- package.json
- yarn.lock
Allows searching for mental health professionals given a zipcode or city.
> Search nearby mental health professionals implementation

- User-Authentication/SignUp.js
Makes new users friends with @kic_team when they first sign up, in order to initially populate their friend recommendations.
> Default friend upon signup

- Tests/MentalHealth.test.js
Added jest testing for mental health log and mood history pages in mentalhealth.test.js testing suit
> Mental health jest testing

- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
- Components/KIC_Image.js
- Components/PostDetails.js
- Components/PostsGrid.js
- Components/ProfileHeader.js
- Components/RequestBlurb.js
- Components/UserBlurb.js
- Personal-Page/FriendsPage.js
- Personal-Page/PersonalPage.js
- Personal-Page/ProfilePost.js
- Personal-Page/RequestsList.js
- Personal-Page/UserPage.js
- package.json
- yarn.lock
-Fix bug where request blurb was not linking to user page
-Fix bug where user could access their pending requests from other users' friends pages
-Add profanity filter to comments
> Various bug fixes

- Components/Comment.js
- Components/CommentSection.js
- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
Comments can now be clicked to be taken to the commenter's profile and postviews are correctly updated when viewing multiple images from the same account
> DPV bug fix and linked comments

- Components/Comment.js
- Components/CommentSection.js
- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
Allows users to enable/disable comments on individual posts and delete their own comments/any comments on their own posts.
> Commenting features

- User-Feed/UserFeedNav.js
Fix bug where friends page wasn't accessible when viewing an account through the user feed
> User feed link bug

- Components/ProfilePicture.js
Allows mobile uploaded profile images to appear correctly on web and mobile
> Profile pic fix

- Components/Comment.js
- Components/DetailedPostView.js
- Components/DetailedPostViewWeb.js
- Components/KIC_Image.js
- Managers/ClientManager.js
- Post/Post.js
- Post/PostInfo.js
-Mobile image uploading/viewing fully functional on iOS and Android
-Video uploading/viewing functional on Android
> Mobile upload fix

- Components/DetailedPostViewWeb.js
- Personal-Page/UserPage.js
- Settings-Page/SettingsPage.js
Ensures that bio change works and styling of private accounts is clean
> Quick fix for bio change and styling
